name: Sync GitHub Issue to Jira
on:
  issues:
    types: [opened]  # Se activa cuando se abre un nuevo issue

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        env:
          JIRA_EMAIL: "tu-email@empresa.com"  # Reemplaza con tu email de Jira
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: "tu-dominio.atlassian.net"  # Ej: "miempresa.atlassian.net"
          JIRA_PROJECT_KEY: "PROJ"  # Clave de tu proyecto en Jira (ej: "DEV")
          ISSUE_TYPE: "Task"  # Tipo de issue en Jira (ej: "Bug")
        run: |
          curl -X POST \
          "https://$JIRA_DOMAIN/rest/api/2/issue" \
          -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "fields": {
              "project": { "key": "$JIRA_PROJECT_KEY" },
              "summary": "${{ github.event.issue.title }}",
              "description": "${{ github.event.issue.body }}",
              "issuetype": { "name": "$ISSUE_TYPE" }
            }
          }'
